// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Framework.EF.Migrations
{
    [DbContext(typeof(ApplicationContextDb))]
    internal class ApplicationContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Framework.EF.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<int>("CreatedBy")
                    .HasColumnType("int");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Email")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Name")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<int>("UpdatedBy")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("Framework.EF.TestAggregate", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<int>("CreatedBy")
                    .HasColumnType("int");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("datetime(6)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("TestName")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<int>("UpdatedBy")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Aggregates");
            });
#pragma warning restore 612, 618
        }
    }
}